"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"

version = 3
final_space = true
auto_upgrade = true
console_title_template = "❯ {{ .Shell }} in {{ .Folder }}"

[palette]
  black = "#000000"
  blue = "#0077c2"
  green = "#6CA35E"
  red = "#ef5350"
  white = "#FFFFFF"
  yellow = "#ffff66"
  orange = "#F59574"

[cache]
  duration = "1h"
  strategy = "session"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "root"
    style = "plain"
    foreground = "p:yellow"
    background = "transparent"
    template = "󱐋 "

  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "p:blue"
    background = "transparent"
    template = "\u256d\u2500\u2500  {{ .Folder }} ❯ "

[[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "p:red"
    background = "transparent"
    template = """ {{ .HEAD }} \
      {{if .BranchStatus }}{{ .BranchStatus }}{{ end }}\
      {{ if .Working.Changed }}  {{ .Working.String }}{{ end }}\
      {{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}\
      {{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} ❯ """

    [blocks.segments.properties]
      fetch_status = true
      fetch_upstream_icon = false
      source = "cli"

  [[blocks.segments]]
    type = "go"
    style = "plain"
    foreground = "p:green"
    background = "transparent"
    template = "ﳑ {{ .Major }}.{{ .Minor }} ❯ "

  [[blocks.segments]]
    type = "java"
    style = "plain"
    foreground = "p:green"
    background = "transparent"
    template = " {{ .Major }}.{{ .Minor }} ❯ "

  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = "p:green"
    template = "  {{ .Major }}.{{ .Minor }} ❯ "

  [[blocks.segments]]
    type = "dotnet"
    style = "plain"
    foreground = "p:green"
    background = "transparent"
    template = "  {{ .Major }}.{{ .Minor }} ❯ "

  [[blocks.segments]]
    type = "lua"
    style = "plain"
    foreground = "p:green"
    template = " {{ .Major }}.{{ .Minor }} ❯ "

  [[blocks.segments]]
    type = "elixir"
    style = "plain"
    foreground = "p:green"
    background = "transparent"
    template = " {{ .Major }}.{{ .Minor }} ❯ "

  [[blocks.segments]]
    type = "react"
    style = "plain"
    foreground = "p:green"
    background = "transparent"
    template = " {{ .Major }}.{{ .Minor }} ❯ "

  [[blocks.segments]]
    type = "angular"
    style = "plain"
    foreground = "p:green"
    background = "transparent"
    template = " {{ .Major }}.{{ .Minor }} ❯ "

[[blocks]]
  type = "prompt"
  alignment = "right"

  [[blocks.segments]]
    type = "time"
    style = "plain"
    foreground = "p:orange"
    template = "{{ .CurrentDate | date \" 15:04:05 \" }}"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "p:blue"
    background = "transparent"
    template = "\u2570\u2500"

    [blocks.segments.properties]
      always_enabled = true
      status_template = "{{ if eq .Code 0 }} \uf00c{{else}} \uf071 {{ reason .Code }}{{ end }}"

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "p:blue"
    template = "\uf054"
