#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 3
final_space = true
console_title_template = "❯ {{ .Shell }} in {{ .Folder }}"

[palette]
  black = "#000000"
  blue = "#0077c2"
  green = "#6CA35E"
  red = "#ef5350"
  white = "#FFFFFF"
  yellow = "#ffff66"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "root"
    style = "plain"
    foreground = "p:yellow"
    background = "transparent"
    template = "󱐋 "

  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "p:blue"
    background = "transparent"
    template = " {{ .Folder }} ❯"

  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "p:red"
    background = "transparent"
    template = "  {{ .HEAD }}{{if .BranchStatus }}{{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} ❯"
    background_templates = ["{{ if or (.Working.Changed) (.Staging.Changed) }}p:red{{ end }}", "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}", "{{ if gt .Ahead 0 }}p:red{{ end }}", "{{ if gt .Behind 0 }}p:red{{ end }}"]

  [[blocks.segments]]
    type = "dotnet"
    style = "plain"
    foreground = "p:green"
    background = "transparent"
    template = "  {{ .Major }}.{{ .Minor }}"

  [[blocks.segments]]
    type = "java"
    style = "plain"
    foreground = "p:green"
    background = "transparent"
    template = "  {{ .Full }}"

  [[blocks.segments]]
    type = "go"
    style = "plain"
    foreground = "p:green"
    background = "transparent"
    template = " ﳑ {{ .Major }}.{{ .Minor }}"

  [[blocks.segments]]
    type = "angular"
    style = "plain"
    foreground = "p:green"
    background = "transparent"
    template = "  {{ .Major }}.{{ .Minor }}"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:green{{end}}",
    ]
    background = "transparent"
    template = "❯"

[transient_prompt]
  type = "text"
  style = "plain"
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:green{{end}}",
  ]
  background = 'transparent'
  template = '❯ '
