version = 3
final_space = true
console_title_template = "{{ .Shell }} in {{ .Folder }}"

[palette]
  black = "#000000"
  blue = "#0077c2"
  green = "#6CA35E"
  red = "#EF5350"
  white = "#FFFFFF"
  yellow = "#ffff66"
  orange = "#F59574"
  gray = "#808080"
  coral = "#CD5C5C"
  dark_gray = "#404040"

[transient_prompt]
  # foreground_templates = [
  #   "{{if gt .Code 0}}p:coral{{end}}",
  #   "{{if eq .Code 0}}p:gray{{end}}",
  # ]
  foreground = "p:dark_gray"
  background = "transparent"
  template = " "

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "path"
    style = "diamond"
    foreground = "p:white"
    background = "p:blue"
    template = "  {{ .Folder }} "
    leading_diamond = ""
    trailing_diamond = ""

  [[blocks.segments]]
    type = "git"
    style = "diamond"
    foreground = "p:white"
    background = "p:red"
    template = """  <b>{{ .HEAD }} \
      {{if .BranchStatus }}{{ .BranchStatus }}{{ end }}\
      {{ if .Working.Changed }}  {{ .Working.String }}{{ end }}\
      {{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}\
      {{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}</b> """
    leading_diamond = "<transparent,p:red></>"
    trailing_diamond = ""

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = "dotnet"
    style = "diamond"
    foreground = "p:white"
    background = "p:green"
    template = "  {{ .Major }}.{{ .Minor }} "
    leading_diamond = "<transparent,p:green></>"
    trailing_diamond = ""

  [[blocks.segments]]
    type = "java"
    style = "diamond"
    foreground = "p:white"
    background = "p:green"
    template = "  {{ .Full }}"
    leading_diamond = "<transparent,p:green></>"
    trailing_diamond = ""

  [[blocks.segments]]
    type = "go"
    style = "diamond"
    foreground = "p:white"
    background = "p:green"
    template = " ﳑ <b>{{ .Major }}.{{ .Minor }}</b> "
    leading_diamond = "<transparent,p:green></>"
    trailing_diamond = ""

  [[blocks.segments]]
    type = "angular"
    style = "diamond"
    foreground = "p:white"
    background = "p:green"
    template = "  {{ .Major }}.{{ .Minor }} "
    leading_diamond = "<transparent,p:green></>"
    trailing_diamond = ""

  [[blocks.segments]]
    type = "root"
    style = "diamond"
    foreground = "p:black"
    background = "p:yellow"
    template = "󱐋"
    leading_diamond = "<transparent,p:yellow></>"
    trailing_diamond = ""

    [blocks.segments.properties]
      cache_duration = "none"

# [[blocks]]
#   type = "prompt"
#   alignment = "left"
#   newline = true

#   [[blocks.segments]]
#     type = "text"
#     style = "plain"
#     foreground = "p:gray"
#     background = "transparent"
#     template = ""
