version = 3
final_space = true
console_title_template = "{{ .Shell }} in {{ .Folder }}"

[palette]
  black = "#000000"
  blue = "#0077c2"
  green = "#6CA35E"
  red = "#ef5350"
  white = "#FFFFFF"
  yellow = "#ffff66"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    leading_diamond = ""
    trailing_diamond = ""
    template = "  {{ .Path }} "
    foreground = "p:white"
    powerline_symbol = ""
    background = "p:blue"
    type = "path"
    style = "diamond"

    [blocks.segments.properties]
      cache_duration = "none"
      style = "folder"

  [[blocks.segments]]
    leading_diamond = ""
#    trailing_diamond = ""
    template = "  {{ .HEAD }} {{if .BranchStatus }}{{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
    foreground = "p:white"
    powerline_symbol = ""
    background = "p:red"
    type = "git"
    style = "powerline"
    background_templates = ["{{ if or (.Working.Changed) (.Staging.Changed) }}p:red{{ end }}", "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}", "{{ if gt .Ahead 0 }}p:red{{ end }}", "{{ if gt .Behind 0 }}p:red{{ end }}"]

    [blocks.segments.properties]
      branch_max_length = 25
      cache_duration = "none"
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
#    leading_diamond = "<transparent,p:green></>"
    trailing_diamond = ""
    template = "  {{ .Major }}.{{ .Minor }} "
    foreground = "p:white"
    background = "p:green"
    type = "dotnet"
    style = "diamond"

    [blocks.segments.properties]
      cache_duration = "none"

  [[blocks.segments]]
#    leading_diamond = "<transparent,p:green></>"
    trailing_diamond = ""
    template = "  {{ .Full }}"
    foreground = "p:white"
    background = "p:green"
    type = "java"
    style = "diamond"

    [blocks.segments.properties]
      cache_duration = "none"

  [[blocks.segments]]
#    leading_diamond = "<transparent,p:green></>"
    trailing_diamond = ""
    template = " ‭ﳑ  {{ .Full }} "
    foreground = "p:white"
    background = "p:green"
    type = "go"
    style = "diamond"

    [blocks.segments.properties]
      cache_duration = "none"

  [[blocks.segments]]
#    leading_diamond = "<transparent,p:green></>"
    trailing_diamond = ""
    template = "  {{ .Major }}.{{ .Minor }} "
    foreground = "p:white"
    background = "p:green"
    type = "angular"
    style = "diamond"

    [blocks.segments.properties]
      cache_duration = "none"

  [[blocks.segments]]
    template = "󱐋"
    foreground = "p:black"
    powerline_symbol = ""
    background = "p:yellow"
    type = "root"
    style = "powerline"

    [blocks.segments.properties]
      cache_duration = "none"