"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"

# Preview
# ╭──  C:\ ❯                                                                           15:39:12
# ╰─

version = 3
final_space = true
auto_upgrade = true
console_title_template = "❯ {{ .Shell }} in {{ .Folder }}"

[palette]
  black = "#000000"
  blue = "#0077c2"
  green = "#6CA35E"
  red = "#EF5350"
  white = "#FFFFFF"
  yellow = "#ffff66"
  orange = "#F59574"
  gray = "#808080"
  coral = "#CD5C5C"
  dark_gray = "#404040"

# [cache]
#   duration = "1h"
#   strategy = "session"

[transient_prompt]
  # foreground_templates = [
  #   "{{if gt .Code 0}}p:coral{{end}}",
  #   "{{if eq .Code 0}}p:gray{{end}}",
  # ]
  foreground = "p:dark_gray"
  background = "transparent"
  template = " "

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "root"
    style = "plain"
    foreground = "p:yellow"
    background = "transparent"
    template = "󱐋 "

  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "p:blue"
    background = "transparent"
    template = "╭──  <b>{{ .Folder }}</b> ❯ "

  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "p:red"
    background = "transparent"
    template = """ <b>{{ .HEAD }} \
      {{if .BranchStatus }}{{ .BranchStatus }}{{ end }}\
      {{ if .Working.Changed }}  {{ .Working.String }}{{ end }}\
      {{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}\
      {{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}</b> ❯ """

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = false

  [[blocks.segments]]
    type = "go"
    style = "plain"
    foreground = "p:green"
    background = "transparent"
    template = "ﳑ <b>{{ .Major }}.{{ .Minor }}</b> ❯ "

  [[blocks.segments]]
    type = "java"
    style = "plain"
    foreground = "p:green"
    background = "transparent"
    template = " <b>{{ .Major }}.{{ .Minor }}</b> ❯ "

  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = "p:green"
    template = "  <b>{{ .Major }}.{{ .Minor }}</b> ❯ "

  [[blocks.segments]]
    type = "dotnet"
    style = "plain"
    foreground = "p:green"
    background = "transparent"
    template = " <b>{{ .Major }}.{{ .Minor }}</b> ❯ "

  [[blocks.segments]]
    type = "lua"
    style = "plain"
    foreground = "p:green"
    template = " <b>{{ .Major }}.{{ .Minor }}</b> ❯ "

  [[blocks.segments]]
    type = "elixir"
    style = "plain"
    foreground = "p:green"
    background = "transparent"
    template = " <b>{{ .Major }}.{{ .Minor }}</b> ❯ "

  [[blocks.segments]]
    type = "react"
    style = "plain"
    foreground = "p:green"
    background = "transparent"
    template = " <b>{{ .Major }}.{{ .Minor }}</b> ❯ "

  [[blocks.segments]]
    type = "angular"
    style = "plain"
    foreground = "p:green"
    background = "transparent"
    template = " <b>{{ .Major }}.{{ .Minor }}</b> ❯ "

[[blocks]]
  type = "prompt"
  alignment = "right"

  [[blocks.segments]]
    type = "time"
    style = "plain"
    foreground = "p:orange"
    template = "{{ .CurrentDate | date .Format }} "

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "p:blue"
    background = "transparent"
    template = "╰─"

  [[blocks.segments]]
    type = "text"
    style = "plain"
    # foreground_templates = [
    #   "{{if gt .Code 0}}p:coral{{end}}",
    #   "{{if eq .Code 0}}p:gray{{end}}",
    # ]
    foreground = "p:gray"
    background = "transparent"
    template = ""
